# Generated by Django 5.2.7 on 2025-10-29 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exchange',
            index=models.Index(fields=['status'], name='main_exchan_status_e4cba9_idx'),
        ),
        migrations.AddIndex(
            model_name='exchange',
            index=models.Index(fields=['user1', 'status'], name='main_exchan_user1_i_6e5725_idx'),
        ),
        migrations.AddIndex(
            model_name='exchange',
            index=models.Index(fields=['user2', 'status'], name='main_exchan_user2_i_5474b0_idx'),
        ),
        migrations.AddIndex(
            model_name='exchange',
            index=models.Index(fields=['-start_date'], name='main_exchan_start_d_39c3b7_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['timestamp'], name='main_messag_timesta_85e3ea_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='main_messag_is_read_04a105_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver', 'is_read'], name='main_messag_receive_8dd99f_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'receiver'], name='main_messag_sender__285ae4_idx'),
        ),
        migrations.AddIndex(
            model_name='userskill',
            index=models.Index(fields=['role'], name='main_usersk_role_1c8ed7_idx'),
        ),
        migrations.AddIndex(
            model_name='userskill',
            index=models.Index(fields=['proficiency'], name='main_usersk_profici_60820b_idx'),
        ),
        migrations.AddIndex(
            model_name='userskill',
            index=models.Index(fields=['user', 'role'], name='main_usersk_user_id_3abe78_idx'),
        ),
    ]
