# Generated by Django 5.2.7 on 2025-10-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_exchange_main_exchan_status_e4cba9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='admin_approved',
            field=models.BooleanField(default=False, help_text='Admin verified both users completed the exchange'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='admin_approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchange',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin notes about this exchange'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='user1_completed',
            field=models.BooleanField(default=False, help_text='User1 marked their part as complete'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='user1_completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchange',
            name='user2_completed',
            field=models.BooleanField(default=False, help_text='User2 marked their part as complete'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='user2_completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
